### ISSUE TITLE
Run_all script hits an error

### ISSUE THREAD

**Issue by URBabylab** [SeedlingsBabylab/datavyu_scripts#5]
---

Running Script: run_all.rb on project: 32_09_coderSD

---

NoMethodError: undefined method `object' for #<RCell:0x1637251>
  (root) at <script>:53
    each at org/jruby/RubyArray.java:1615
  (root) at <script>:52
    each at org/jruby/RubyArray.java:1615
  (root) at <script>:50
(NoMethodError) undefined method`object' for #RCell:0x1637251

****\* SCRIPT ERROR *****

NoMethodError: undefined method `object' for #RCell:0x1637251
  (root) at <script>:53
    each at org/jruby/RubyArray.java:1615
  (root) at <script>:52
    each at org/jruby/RubyArray.java:1615
  (root) at <script>:50

See line 50 of /Volumes/seedlings/Scripts_and_Apps/github/datavyu_scripts/run_all.rb:
    for column in columns
See line 52 of /Volumes/seedlings/Scripts_and_Apps/github/datavyu_scripts/run_all.rb:
        for cell in col.cells
See line 53 of /Volumes/seedlings/Scripts_and_Apps/github/datavyu_scripts/run_all.rb:
            if (cell.object.to_s.start_with?("%com:") &&

**Comment by URBabylab** [comment]
And by the way, I'm on Azalea!

**Comment by andreiamatuni** [comment]
This could be because "object" is misspelled in the codes that are entered at the beginning in the code editor, or if you use a different word in its place. The script is basically complaining that it doesn't recognize a code named "object"

**Comment by URBabylab** [comment]
Hey it's Munna, not sure what is going on in here but here's a summary of this problem:
- replicated in macs and pcs
- replicated in old and new versions of datavyu
- "object" not misspelled in any of the datavyu script codes

This is super high priority btw so it'd be awesomeee if you could get to it asap!

**Comment by andreiamatuni** [comment]
I just checked 32_09_coderSD and the label for the object code is called "labeled_object" rather than "object". If you change it to "object" in the code editor, the run_all script runs fine (at least it just did on my computer)

**Comment by andreiamatuni** [comment]
code editor = Spreadsheet -> CodeEditor (in the datavyu program)
