### ISSUE TITLE
need to allow for new kind of comment in checking scripts

### ISSUE THREAD

**Issue by ebergelson** [SeedlingsBabylab/datavyu_scripts#8]
There's a new kind of comment cell that check should allow
  a. in the '''object code''' : %com: mwu
  a. in the '''utterance_type code''', '''in quotes''', what the child said, e.g."It's my juice cup!"
  a. NA in the 3rd and 4th codes
- For instance, one cell may look like this: %com: mwu, "It's my juice cup!", NA, NA
  and that should pass check

**Comment by ebergelson** [comment]
(see 08_17 for an example video coding file for this)

**Comment by andreiamatuni** [comment]
fixed with 8ce4db3529f4deb1474447607ca608416d41a1ae
